Repository it-novum/openITCOCKPIT, pull requests merged in 2020-10, with the labels that each got.

#1063 Telegram module
  plugins/TelegramModule/.gitignore
  plugins/TelegramModule/LICENSE
  plugins/TelegramModule/README.md
  plugins/TelegramModule/composer.json
  plugins/TelegramModule/config/Migrations/20200918221811_Initial.php
  plugins/TelegramModule/config/Seeds/InstallSeed.php
  plugins/TelegramModule/phpunit.xml.dist
  plugins/TelegramModule/src/Command/TelegramNotificationCommand.php
  plugins/TelegramModule/src/Command/TelegramProcessUpdatesCommand.php
  plugins/TelegramModule/src/Controller/AppController.php
  plugins/TelegramModule/src/Controller/TelegramSettingsController.php
  plugins/TelegramModule/src/Controller/TelegramWebhookController.php
  plugins/TelegramModule/src/Lib/AclDependencies.php
  plugins/TelegramModule/src/Lib/Menu.php
  plugins/TelegramModule/src/Lib/TelegramActions.php
  plugins/TelegramModule/src/Model/Entity/TelegramChats.php
  plugins/TelegramModule/src/Model/Entity/TelegramSetting.php
  plugins/TelegramModule/src/Model/Table/TelegramChatsTable.php
  plugins/TelegramModule/src/Model/Table/TelegramSettingsTable.php
  plugins/TelegramModule/src/Plugin.php
  plugins/TelegramModule/templates/TelegramSettings/index.php
  plugins/TelegramModule/webroot/.gitkeep
  plugins/TelegramModule/webroot/js/scripts/controllers/TelegramSettingsIndexController.js
  plugins/TelegramModule/webroot/js/scripts/ng.states.js
  src/Lib/PluginManager.php
Labels: Requires QA

#1067 Telegram module
  plugins/TelegramModule/.gitignore
  plugins/TelegramModule/LICENSE
  plugins/TelegramModule/README.md
  plugins/TelegramModule/composer.json
  plugins/TelegramModule/config/Migrations/20200918221811_Initial.php
  plugins/TelegramModule/config/Seeds/InstallSeed.php
  plugins/TelegramModule/phpunit.xml.dist
  plugins/TelegramModule/src/Command/TelegramNotificationCommand.php
  plugins/TelegramModule/src/Command/TelegramProcessUpdatesCommand.php
  plugins/TelegramModule/src/Controller/AppController.php
  plugins/TelegramModule/src/Controller/TelegramSettingsController.php
  plugins/TelegramModule/src/Controller/TelegramWebhookController.php
  plugins/TelegramModule/src/Lib/AclDependencies.php
  plugins/TelegramModule/src/Lib/Menu.php
  plugins/TelegramModule/src/Lib/TelegramActions.php
  plugins/TelegramModule/src/Model/Entity/TelegramChats.php
  plugins/TelegramModule/src/Model/Entity/TelegramSetting.php
  plugins/TelegramModule/src/Model/Table/TelegramChatsTable.php
  plugins/TelegramModule/src/Model/Table/TelegramSettingsTable.php
  plugins/TelegramModule/src/Plugin.php
  plugins/TelegramModule/templates/TelegramSettings/index.php
  plugins/TelegramModule/webroot/.gitkeep
  plugins/TelegramModule/webroot/js/scripts/controllers/TelegramSettingsIndexController.js
  plugins/TelegramModule/webroot/js/scripts/ng.states.js
  src/Lib/PluginManager.php
Labels: Requires QA, hacktoberfest-accepted

#1071 ITC-1307
  src/Controller/HostsController.php
  src/Template/Hosts/browser.php
  src/Template/Services/browser.php
  src/itnovum/openITCOCKPIT/Core/Hoststatus.php
  src/itnovum/openITCOCKPIT/Core/Servicestatus.php
Labels: hacktoberfest-accepted
